# Configure main, social, and contact menus
[[main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[main.params]
icon = "home"
#newtab = true

[[main]]
identifier = "cv"
name = "CV"
url = "/cv/main.pdf"
weight = 3
[main.params]
icon= "file-user"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/fthdrmzzz"

[social.params]
icon = "brand-github"

[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://linkedin.com/in/fthdrmzzz"

[social.params]
icon = "linkedin"

[[social]]
identifier = "gscholar"
name = "Google Scholar"
url = "https://scholar.google.com/citations?user=QVHavYYAAAAJ&hl=en"

[social.params]
icon = "google-scholar"

[[contact]]
identifier = "email"
name = "Email"
url = "mailto:mail.fatih.durmaz@gmail.com"
weight = 1

[contact.params]
icon = "mail"
newTab = false

[[contact]]
identifier = "appointment"
name = "Appointment"
url = "https://www.cal.eu/fatih.durmaz/30minappointment"
weight = 2

[contact.params]
icon = "appointment"
newTab = true
